#!/bin/bash
ls -1p | { [System.Collections.ArrayList]$files = @(); [System.Collections.ArrayList]$directories = @(); foreach ($item in $_) { if ($item -match '^[A-Za-z0-9]') { if ($item -like '*/*') { $directories.Add($item+'/') } else { $files.Add($item) } } } $directories.Sort(); $files.Sort(); $directories.InsertRange(0,('.', '..')); $directories + $files -join ',' }

